name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Run Build Script
      run: |
        export ANDROID_SDK=${ANDROID_SDK_ROOT}
        ./build.sh
